# Copyright 2024 Cisco Systems, Inc. and its affiliates
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

---

- name: Inform user that PnP Portal sync requires certain manual input
  ansible.builtin.pause:
    prompt: |-

      Please verify that your PnP Portal Controller Profile is up to date with vbond and organization name.

      vBond_transport_public_ip:
          {{ vbond_transport_public_ip }}
      organization_name:
          {{ organization_name }}

      Press any key to continue, press `Ctrl + C` and `Shift + A` to abort
  register: user_response

- name: Verify required variables for selected role
  ansible.builtin.include_tasks: variables_assertion.yml

- name: Set initial configuration via administration settings - loop through all vManage devices
  cisco.catalystwan.administration_settings:
    validator:
      domain_ip: "{{ vbond_transport_public_ip }}"
      port: "{{ validator_port }}"
    organization: "{{ organization_name }}"
    certificates:
      retrieve_interval: "2"
    pnp_connect_sync: "on"
    smart_account_credentials:
      username: "{{ pnp_username }}"
      password: "{{ pnp_password }}"
    manager_authentication:
      url: "{{ device_item.mgmt_public_ip }}"
      username: "{{ device_item.admin_username }}"
      password: "{{ device_item.admin_password }}"
  loop: "{{ vmanage_instances }}"
  loop_control:
    loop_var: device_item
    label: "hostname: {{ device_item.hostname }}, device_ip: {{ device_item.system_ip }}"
#  retries: 12
#  delay: 10
